class Fish
  TYPES =
    [
      "Walleye",
      "Lake Trout",
      "Lake Sturgeon",
      "Sea Lamprey",
      "Bighead Carp",
      "American brook lamprey",
      "Silver lamprey",
      "Northern brook lamprey",
      "Chestnut lamprey",
      "American eel",
      "Bowfin",
      "Burbot",
      "Lake herring",
      "Lake whitefish",
      "Bloater",
      "Kiyi",
      "Coho salmon",
      "Rainbow trout",
      "Steelhead trout",
      "Chinook salmon",
      "Atlantic salmon",
      "Brown trout",
      "Brook trout",
      "Spotted gar",
      "Longnose gar",
      "Shortnose gar",
      "Northern pike",
      "Muskellunge",
      "Grass pickerel",
      "Chain pickerel",
      "Rock bass",
      "Pumpkinseed",
      "Bluegill",
      "Green sunfish",
      "Smallmouth bass",
      "Largemouth bass",
      "White crappie",
      "Black crappie",
      "White perch",
      "White bass",
      "Yellow bass",
      "Yellow perch",
      "Sauger",
      "White sucker",
      "Black bullhead",
      "Common carp",
      "Silver carp",
      "Channel catfish",
      "Smallmouth buffalo",
      "Freshwater drum",
      "Grass carp",
      "Brown bullhead",
      "Quillback",
      "Mottled sculpin",
      "Slimy sculpin",
      "Spoonhead sculpin",
      "Deepwater sculpin",
      "Blue catfish",
      "Paddlefish",
      "Pallid sturgeon",
      "Shovelnose sturgeon",
      "Hybrid Asian carp"
    ]

  SCITYPES =
    [
      "Sander vitreus",
      "Salvelinus namaycush",
      "Acipenser fulvescens",
      "Petromyzon marinus",
      "Hypophthalmichthys nobilis",
      "Lampetra appendix",
      "Ichthyomyzon unicuspis",
      "Ichthyomyzon fossor",
      "Ichthyomyzon castaneus",
      "Anguilla rostrata",
      "Amia calva",
      "Lota lota",
      "Coregonus artedi",
      "Coregonus clupeaformis",
      "Coregonus hoyi",
      "Coregonus kiyi",
      "Oncorhynchus kisutch",
      "Oncorhynchus mykiss",
      "Oncorhynchus mykiss",
      "Oncorhynchus tshawtscha",
      "Salmo salar",
      "Salmo trutta",
      "Salvelinus fontinalis",
      "Lepisosteus oculatus",
      "Lepisosteus osseus",
      "Lepisosteus platostomus",
      "Esox lucius",
      "Esox masquinongy",
      "Esox americanus vermiculatus",
      "Esox niger",
      "Ambloplites rupestris",
      "Lepomis gibbosus",
      "Lepomis macrochirus",
      "Lepomis cyanellus",
      "Micropterus dolomieu",
      "Micropterus salmoides",
      "Pomoxis annularis",
      "Pomoxis nigromaculatus",
      "Morone americana",
      "Morone chrysops",
      "Morone mississippiensis",
      "Perca flavescens",
      "Sander canadensis",
      "Catastomus commersoni",
      "Ameiurus melas",
      "Cyprinus carpio",
      "Hypophthalmichthys molitrix",
      "Ictalurus punctatus",
      "Ictiobus bubalus",
      "Aplodinotus grunniens",
      "Ctenopharyngodon idella",
      "Ameiurus nebulosus",
      "Carpiodes cyprinus",
      "Cottus bairdi",
      "Cottus cognatus",
      "Cottus ricei",
      "Myoxocephalus thompsoni",
      "Ictalurus furcatus",
      "Polyodon spathula",
      "Scaphirhynchus albus",
      "Scaphirhynchus platorynchus",
      "Hypophthalmichthys spp."  
    ]

  SEX =
    [
      "Male",
      "Female"
    ]

  WOH =
    [
      "Wild",
      "Hatchery"
    ]
end
