class State
  NAMES =
    [
      [ "Alberta", "AB"],
      [ "British Columbia", "BC"],
      [ "Illinois", "IL" ],
      [ "Manitoba", "MB"],
      [ "Michigan", "MI" ],
      [ "New York", "NY" ],
      [ "Newfoundland And Labrador", "NL"],
      [ "Nova Scotia", "NS"],
      [ "New Brunswick", "NB"],
      [ "Ohio", "OH" ],
      [ "Ontario", "ON"],
      [ "Pennsylvania", "PA" ],
      [ "Price Edward Island", "PE"],
      [ "Quebec", "QC"],
      [ "Saskatchewan", "SK"],
      [ "Wisconsin", "WI" ],

      [ "Alabama", "AL" ],
      [ "Alaska", "AK" ],
      [ "Arizona", "AZ" ],
      [ "Arkansas", "AR" ],
      [ "California", "CA" ],
      [ "Colorado", "CO" ],
      [ "Connecticut", "CT" ],
      [ "Delaware", "DE" ],
      [ "District Of Columbia", "DC" ],
      [ "Florida", "FL" ],
      [ "Georgia", "GA" ],
      [ "Hawaii", "HI" ],
      [ "Idaho", "ID" ],
      [ "Indiana", "IN" ],
      [ "Iowa", "IA" ],
      [ "Kansas", "KS" ],
      [ "Kentucky", "KY" ],
      [ "Louisiana", "LA" ],
      [ "Maine", "ME" ],
      [ "Maryland", "MD" ],
      [ "Massachusetts", "MA" ],
      [ "Minnesota", "MN" ],
      [ "Mississippi", "MS" ],
      [ "Missouri", "MO" ],
      [ "Montana", "MT" ],
      [ "Nebraska", "NE" ],
      [ "Nevada", "NV" ],
      [ "New Hampshire", "NH" ],
      [ "New Jersey", "NJ" ],
      [ "New Mexico", "NM" ],
      [ "North Carolina", "NC" ],
      [ "North Dakota", "ND" ],
      [ "Oklahoma", "OK" ],
      [ "Oregon", "OR" ],
      [ "Rhode Island", "RI" ],
      [ "South Carolina", "SC" ],
      [ "South Dakota", "SD" ],
      [ "Tennessee", "TN" ],
      [ "Texas", "TX" ],
      [ "Utah", "UT" ],
      [ "Vermont", "VT" ],
      [ "Virginia", "VA" ],
      [ "Washington", "WA" ],
      [ "West Virginia", "WV" ],
      [ "Wyoming", "WY" ]
    ]
end
